import os

ROOT_DIR = os.path.dirname(os.path.dirname(__file__))

DATA_DIR = os.path.join(ROOT_DIR, "data")
OUTPUT_DIR = os.path.join(ROOT_DIR, "output")

RAW_DIR = os.path.join(DATA_DIR, "raw")
EXCEL_OUTPUT_DIR = os.path.join(RAW_DIR, "ExcelOutput")
TEXTMAP_DIR = os.path.join(RAW_DIR, "TextMap")

IMAGE_DIR = os.path.join(OUTPUT_DIR)
ENABLE_WEBP_CONVERSION = True
ENABLE_IMAGE = True

INDEX_DIR = os.path.join(OUTPUT_DIR, "index_new")
INDEX_DIR_MIN = os.path.join(OUTPUT_DIR, "index_min")

LANGUAGES = ["CHS", "CHT", "DE", "EN", "ES", "FR", "ID", "JP", "KR", "PT", "RU", "TH", "VI"]

AVATAR_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarConfig.json")  # Pour characters.json ✅ et nickname.json ✅
AVATAR_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarConfigLD.json")  # Pour characters.json ✅
AVATAR_ENHANCED_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarConfigEnhanced.json")  # Pour characters.json ✅

ACHIEVEMENT_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AchievementData.json")  # Pour achievements.json ✅

AVATAR_PROMOTION_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                          "AvatarPromotionConfig.json")  # Pour character_promotions.json ✅
AVATAR_PROMOTION_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                             "AvatarPromotionConfigLD.json")  # Pour character_promotions.json ✅

AVATAR_SKILL_TREE_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                           "AvatarSkillTreeConfig.json")  # Pour character_skill_trees.json ✅
AVATAR_SKILL_TREE_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                              "AvatarSkillTreeConfigLD.json")  # Pour character_skill_trees.json ✅

MESSAGE_CONTACTS_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "MessageContactsConfig.json")  # Pour avatars.json ✅
ITEM_PLAYER_CARD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "ItemPlayerCard.json")  # Pour avatars.json ✅
ITEM_CONFIG_AVATAR_PLAYER_ICON_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                                        "ItemConfigAvatarPlayerIcon.json")  # Pour avatars.json ✅
ITEM_CONFIG_AVATAR_PLAYER_ICON_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                                           "ItemConfigAvatarPlayerIcLD.json")  # Pour avatars.json ✅

AVATAR_RANK_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarRankConfig.json")  # Pour character_ranks.json ✅
AVATAR_RANK_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarRankConfigLD.json")  # Pour character_ranks.json ✅

AVATAR_SKILL_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarSkillConfig.json")  # Pour character_skills.json ✅
AVATAR_SKILL_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarSkillConfigLD.json")  # Pour character_skills.json ✅
AVATAR_SERVANT_SKILL_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                              "AvatarServantSkillConfig.json")  # Pour character_skills.json ✅

LOADING_DESC_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "LoadingDesc.json")  # Pour descriptions.json ✅

DAMAGE_TYPE_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "DamageType.json")  # Pour elements.json ✅

ITEM_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "ItemConfig.json")  # Pour items.json ✅
ITEM_BOOK_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "ItemConfigBook.json")  # Pour items.json ✅
ITEM_DISK_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "ItemConfigDisk.json")  # Pour items.json ✅

ITEM_COME_FROM_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "ItemComefrom.json")  # Pour items.json ✅

EQUIPEMENT_PROMOTION_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                              "EquipmentPromotionConfig.json")  # Pour light_cone_promotions.json ✅

EQUIPEMENT_SKILL_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "EquipmentSkillConfig.json")  # Pour light_cone_ranks.json ✅

ITEM_EQUIPEMENT_CONFIG_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "ItemConfigEquipment.json")  # Pour light_cones.json ✅
EQUIPEMENT_CONFIG_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                           "EquipmentConfig.json")  # Pour light_cones.json ✅ et nickname.json ✅

AVATAR_BASE_TYPE_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarBaseType.json")  # paths.json ✅

AVATAR_PROPERTY_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarPropertyConfig.json")  # properties.json ✅

RELIC_MAIN_AFFIX_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RelicMainAffixConfig.json")  # relic_main_affixes.json ✅

RELIC_SET_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RelicSetConfig.json")  # relic_sets.json ✅ et nickname.json ✅
RELIC_SET_SKILL_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RelicSetSkillConfig.json")  # relic_sets.json ✅

RELIC_SUB_AFFIX_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RelicSubAffixConfig.json")  # relic_sub_affixes.json ✅

RELIC_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RelicConfig.json")  # relics.json ✅
ITEM_RELIC_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "ItemConfigRelic.json")  # relics.json ✅

ROGUE_MAZE_BUFF_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RogueMazeBuff.json")  # simulated_blessings.json ✅

ROGUE_DLC_BLOCK_INTRO_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RogueDLCBlockIntro.json")  # simulated_blocks.json ✅

ROGUE_MIRACLE_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RogueMiracle.json")  # simulated_curios.json ✅
ROGUE_MIRACLE_DISPLAY_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RogueMiracleDisplay.json")  # simulated_curios.json ✅
ROGUE_MIRACLE_EFFECT_DISPLAY_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                                      "RogueMiracleEffectDisplay.json")  # simulated_curios.json ✅

ROGUE_TALK_NAME_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RogueTalkNameConfig.json")  # simulated_events.json ✅
ROGUE_IMAGE_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "RogueImage.json")  # simulated_events.json ✅

# Bonus AvatarRelicRecommend
AVATAR_RELIC_RECOMMEND_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarRelicRecommend.json")  # 🔃
AVATAR_RELIC_RECOMMEND_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR,
                                                   "AvatarRelicRecommendLD.json")  # 🔃

# Bonus AvatarServantConfig
AVATAR_SERVANT_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarServantConfig.json")  # 🔃

# Bonus Trace useds
AVATAR_USE_MATERIAL_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarUseMaterialData.json")  # 🔃
AVATAR_USE_MATERIAL_LD_JSON_PATH = os.path.join(EXCEL_OUTPUT_DIR, "AvatarUseMaterialDataLD.json")  # 🔃
